### ISSUE TITLE
go的测试例子不公平

### ISSUE THREAD

**Issue by RelicOfTesla** [xiaojiaqi/C1000kPracticeGuide#3]
测试例子里的go源码，是每接受一个链接就开一个coroutine，相当于变相一个链接开一个线程。
一个goroutine得4k的内存呢，其所用的内存空间肯定是你走epoll的NNN倍，

**Comment by xiaojiaqi** [comment]
但是这样代码简洁了很多倍。你可以给个不用这么多内存的pull request
