### ISSUE TITLE
your's code write mess, no comment, test module is so bad.

### ISSUE THREAD

**Issue by Jayhello** [xiaojiaqi/C1000kPracticeGuide#4]
But still thank for your code

**Comment by xiaojiaqi** [comment]
code without comments? 
agree.  
a bad testing client? 
largely agree.  
mess?
No!

**Comment by Jayhello** [comment]
I runs your code in the directory code->cppserver->src
and then write a client to send msg to the server, get no reply.
and log in the client_read_fun
![image](https://user-images.githubusercontent.com/16144935/28403956-c2fb6982-6d59-11e7-9aaa-f244ddc7d427.png)

if you write code in c++, highly recommend you to use namespace, class, c++11 new feature

**Comment by xiaojiaqi** [comment]
Please check out "Draft 0.1"  or update the source code. commit 59e13f3b48a5a13c2156e3897403e87e1a723de9 is a bug. I can't remember what happened then.

**Comment by innerr** [comment]
Well, grammar error on the title: "your code", not "your's code", and you should use capital “Y”

**Comment by innerr** [comment]
write mess => is mess

**Comment by innerr** [comment]
Thank for => Thanks for
